# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUi(object):
    def setupUi(self, JarvisUi):
        JarvisUi.setObjectName("JarvisUi")
        JarvisUi.resize(1920, 1080)
        self.bg_1 = QtWidgets.QLabel(JarvisUi)
        self.bg_1.setGeometry(QtCore.QRect(-120, -20, 2051, 1131))
        self.bg_1.setText("")
        self.bg_1.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/B.G/Black_Template.jpg"))
        self.bg_1.setScaledContents(True)
        self.bg_1.setObjectName("bg_1")
        self.gif3 = QtWidgets.QLabel(JarvisUi)
        self.gif3.setGeometry(QtCore.QRect(-10, 0, 391, 151))
        self.gif3.setText("")
        self.gif3.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/initial.gif"))
        self.gif3.setScaledContents(True)
        self.gif3.setObjectName("gif3")
        self.gif2 = QtWidgets.QLabel(JarvisUi)
        self.gif2.setGeometry(QtCore.QRect(20, 300, 431, 251))
        self.gif2.setText("")
        self.gif2.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/Code_Template.gif"))
        self.gif2.setScaledContents(True)
        self.gif2.setObjectName("gif2")
        self.gif4 = QtWidgets.QLabel(JarvisUi)
        self.gif4.setGeometry(QtCore.QRect(10, 660, 451, 361))
        self.gif4.setText("")
        self.gif4.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/VoiceReg/Aqua.gif"))
        self.gif4.setScaledContents(True)
        self.gif4.setObjectName("gif4")
        self.gif5 = QtWidgets.QLabel(JarvisUi)
        self.gif5.setGeometry(QtCore.QRect(470, 290, 991, 601))
        self.gif5.setText("")
        self.gif5.setPixmap(QtGui.QPixmap("../../Downloads/LIVE WALLPAPER _ AI JARVIS - IRON-MAN _ STATUS REALM _ PC_DESKTOP _ (Download link in description).gif"))
        self.gif5.setScaledContents(True)
        self.gif5.setObjectName("gif5")
        self.gif6 = QtWidgets.QLabel(JarvisUi)
        self.gif6.setGeometry(QtCore.QRect(1490, 330, 411, 251))
        self.gif6.setText("")
        self.gif6.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/Hero_Template.gif"))
        self.gif6.setScaledContents(True)
        self.gif6.setObjectName("gif6")
        self.gif8 = QtWidgets.QLabel(JarvisUi)
        self.gif8.setGeometry(QtCore.QRect(1480, 610, 421, 241))
        self.gif8.setAutoFillBackground(False)
        self.gif8.setText("")
        self.gif8.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/Health_Template.gif"))
        self.gif8.setScaledContents(True)
        self.gif8.setObjectName("gif8")
        self.gif1 = QtWidgets.QLabel(JarvisUi)
        self.gif1.setGeometry(QtCore.QRect(1500, 40, 361, 251))
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/Jarvis_Gui (1).gif"))
        self.gif1.setScaledContents(True)
        self.gif1.setObjectName("gif1")
        self.gif7 = QtWidgets.QLabel(JarvisUi)
        self.gif7.setGeometry(QtCore.QRect(460, 0, 311, 261))
        self.gif7.setText("")
        self.gif7.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/ExtraGui/Earth.gif"))
        self.gif7.setScaledContents(True)
        self.gif7.setObjectName("gif7")
        self.gif11 = QtWidgets.QLabel(JarvisUi)
        self.gif11.setGeometry(QtCore.QRect(1480, 970, 420, 71))
        self.gif11.setText("")
        self.gif11.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/B.G/gggf.jpg"))
        self.gif11.setScaledContents(True)
        self.gif11.setObjectName("gif11")
        self.gif11_2 = QtWidgets.QLabel(JarvisUi)
        self.gif11_2.setGeometry(QtCore.QRect(1480, 880, 421, 71))
        self.gif11_2.setText("")
        self.gif11_2.setPixmap(QtGui.QPixmap("../../Downloads/jarvis zip/B.G/gggf.jpg"))
        self.gif11_2.setScaledContents(True)
        self.gif11_2.setObjectName("gif11_2")
        self.pushButton_start = QtWidgets.QPushButton(JarvisUi)
        self.pushButton_start.setGeometry(QtCore.QRect(760, 930, 191, 51))
        self.pushButton_start.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 20pt \"Times New Roman\";\n"
"color: rgb(0, 243, 255);\n"
"border-radius:none;")
        self.pushButton_start.setObjectName("pushButton_start")
        self.label = QtWidgets.QLabel(JarvisUi)
        self.label.setGeometry(QtCore.QRect(740, 910, 441, 91))
        self.label.setStyleSheet("background-color: rgb(0, 251, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_exit = QtWidgets.QPushButton(JarvisUi)
        self.pushButton_exit.setGeometry(QtCore.QRect(970, 930, 191, 51))
        self.pushButton_exit.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 20pt \"Times New Roman\";\n"
"color: rgb(0, 243, 255);\n"
"border-radius:none;")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.bg_1.raise_()
        self.label.raise_()
        self.pushButton_start.raise_()
        self.pushButton_exit.raise_()
        self.gif3.raise_()
        self.gif2.raise_()
        self.gif4.raise_()
        self.gif5.raise_()
        self.gif7.raise_()
        self.gif1.raise_()
        self.gif6.raise_()
        self.gif8.raise_()
        self.gif11_2.raise_()
        self.gif11.raise_()

        self.retranslateUi(JarvisUi)
        QtCore.QMetaObject.connectSlotsByName(JarvisUi)

    def retranslateUi(self, JarvisUi):
        _translate = QtCore.QCoreApplication.translate
        JarvisUi.setWindowTitle(_translate("JarvisUi", "Dialog"))
        self.pushButton_start.setText(_translate("JarvisUi", "START"))
        self.pushButton_exit.setText(_translate("JarvisUi", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUi = QtWidgets.QDialog()
    ui = Ui_JarvisUi()
    ui.setupUi(JarvisUi)
    JarvisUi.show()
    sys.exit(app.exec_())
